CREATE TABLE PERSON (
		ID INTEGER NOT NULL,
		AGE INTEGER NOT NULL,
		NAME VARCHAR(255) NOT NULL,
		PRIMARY KEY(ID)
		
);

INSERT INTO PERSON VALUES (1,10, 'Foo10');
INSERT INTO PERSON VALUES (2,20, 'Foo20');
INSERT INTO PERSON VALUES (3,30, 'Foo30');
INSERT INTO PERSON VALUES (4,40, 'Foo40');
INSERT INTO PERSON VALUES (5,50, 'Foo50');





